spring:
  servlet:
     multipart:
       enabled: true
       max-file-size: 10MB
       max-request-size: 20MB
       file-size-threshold: 2KB
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:46935/railway
    username: postgres
    password: 2*44gE3Fgg-Gf2*e3b6G*5dB5DgF4cd-
    driver-class-name: org.postgresql.Driver
  #  datasource:
#    password: elyor1202
#    username: postgres
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /swagger-ui
jwt:
  secret-key: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5ODkyNjc4OSwiaWF0IjoxNjk4OTI2Nzg5fQrxdBCl7Ie3McdHN6VWus1rdrRQywMBCw1o7ZzKKiQj0
  expired: 86400000

#server:
#  ssl:
#    key-store: classpath:keystore.p12
 #   key-store-password: ElyorAzimov
  # key-store-type: PKCS12
 #   key-alias: mycert

